### ISSUE TITLE
Documentation for ignoreLoadingBar

### ISSUE THREAD

**Issue by makkart** [aitboudad/ngx-loading-bar#49]
Can see the implementation in the source code but cannot figure out how to use it with Http-Client and passing of metadata. Would be nice with some documentation and usage example for the feature. Thanks.

**Comment by aitboudad** [comment]
done https://github.com/aitboudad/ngx-loading-bar#ignoring-particular-requests, also you need to update to `1.1.0` version

**Comment by makkart** [comment]
Wow, you are fast :) Thanks!

**Comment by emeryowa** [comment]
The documentation around ignoreLoadingBar is still unclear to me.
I'm using http and I can't get it to work.

Using
```
http.get('/status', {
  options: { params: { ignoreLoadingBar: true } }
});
```
like in the docs does not work because this is not a valid [RequestOptionsArgs](https://angular.io/api/http/RequestOptionsArgs) object to Angular


Using 
```
http.get('/status', {
  params: { ignoreLoadingBar: true }
});
```
is valid and the ignoreLoadingBar is added to the query params but the loading bar still shows.

See https://stackblitz.com/edit/angular-y11dst?file=app/app.service.ts

Is this a bug or should I implement this differently?

**Comment by aitboudad** [comment]
update into `1.2.0` and try with the following code:

```ts
http.get('/status', {
  { headers: new Headers({ ignoreLoadingBar: '' }) }
});
```
